#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

dirs=(
  ".aion/context"
  ".aion/rules"
  ".aion/templates"
  ".github/ISSUE_TEMPLATE"
  ".github/workflows"
  "apps/web"
  "apps/api"
  "apps/admin"
  "services"
  "packages/sdk"
  "packages/shared"
  "packages/config"
  "docs/00-overview"
  "docs/01-product"
  "docs/02-business"
  "docs/03-requirements"
  "docs/04-architecture"
  "docs/05-ai"
  "docs/06-factories"
  "docs/07-integrations"
  "docs/08-data"
  "docs/09-security"
  "docs/10-quality"
  "docs/11-operations"
  "docs/12-roadmap"
  "architecture/adrs"
  "architecture/rfcs"
  "architecture/diagrams"
  "api/openapi"
  "api/asyncapi"
  "database/migrations"
  "database/seeds"
  "database/schemas"
  "prompts/system"
  "prompts/agents"
  "prompts/workflows"
  "workflows/definitions"
  "workflows/examples"
  "infrastructure/docker"
  "infrastructure/kubernetes/base"
  "infrastructure/kubernetes/overlays/dev"
  "infrastructure/kubernetes/overlays/staging"
  "infrastructure/kubernetes/overlays/prod"
  "infrastructure/terraform"
  "scripts/dev"
  "scripts/ci"
  "scripts/ops"
  "tests/unit"
  "tests/integration"
  "tests/e2e"
  "tests/fixtures"
  "data/samples"
  "data/generated"
  "data/cache"
)

for dir in "${dirs[@]}"; do
  ensure_dir "${AION_ROOT}/${dir}"
  if [[ "${dir}" == data/* || "${dir}" == database/seeds ]]; then
    write_file_if_missing "${AION_ROOT}/${dir}/.gitkeep" ""
  fi
done

write_file_if_missing "${AION_ROOT}/VERSION" "0.1.0"
write_file_if_missing "${AION_ROOT}/LICENSE" "Proprietary - All rights reserved."
